# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set a working directory
WORKDIR /app

# Copy all files to the container
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir mcp[cli] httpx pydantic python-dotenv

# Set environment variables placeholders (they will be overridden by startCommand config)
ENV NAVER_CLIENT_ID=your_client_id_here
ENV NAVER_CLIENT_SECRET=your_client_secret_here

# Command to run the MCP server
CMD ["python", "server.py"]
